### ISSUE TITLE
how do i get the text in the editor?

### ISSUE THREAD

**Issue by timo** [azawawi/perl6-gtk-scintilla#1]
I wanted to port my little cairo live coding thing to use scintilla, but i couldn't figure out how to get at the text that's in the editor? :(

**Comment by azawawi** [comment]
I started working on https://github.com/azawawi/perl6-gtk-scintilla/blob/master/tools/generate-code.pl6 and did not complete it due to being overloading with swift/Android/Java projects at work :-1: Bascially there is a file called `scintilla.iface` which has the documentation and function signature.

**Comment by azawawi** [comment]
@timo You can use `get-text` editor method now. Sorry for the delay.
